name: MLOps CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Python 3.12.3
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: DVC Pull
      run: |
        dvc pull

    - name: Test with pytest
      run: |
        pytest
    
    - name: Generate CML report
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Create a report in a markdown file
        echo "## MLOps Week 4 Report" > report.md
        echo "### Pytest Results" >> report.md
        echo "\`\`\`" >> report.md
        pytest >> report.md
        echo "\`\`\`" >> report.md

        # Send the report as a comment
        cml-send-comment report.md